site_name: PyTexas Conference Runbooks
theme:
  name: material
  logo: assets/images/favicon.png
  custom_dir: overrides
  features:
    - navigation.tracking
    - toc.integrate
    - toc.follow
    - navigation.footer
  palette:
    primary: blue
    accent: yellow
copyright: Copyright &copy; 2023 - PyTexas Foundation

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Roles: 
    - Conference Chair: roles/conf-chair.md
    - Program Chair: roles/prog-chair.md
    - Finance Chair: roles/fin-chair.md
    - Sponsorship Chair: roles/spon-chair.md
    - Marketing & Social Chair: roles/mark-chair.md
    - Virtual Chair: roles/virt-chair.md
    - Volunteer & Venue Chair: roles/vol-chair.md
  - Runbooks:
    - Attendee Feedback: runbooks/feedback.md
    - Call for Proposals: runbooks/cfp.md
    - Catering: runbooks/catering.md
    - Code of Conduct: runbooks/coc.md
    - Keynote Selection: runbooks/keynote.md
    - Opportunity Grants: runbooks/grants.md
    - Registration: runbooks/registration.md
    - Sponsorship: runbooks/sponsorship.md
    - Swag: runbooks/swag.md
    - Venue Booking: runbooks/venue.md
    
  - Full Event Timeline: timeline.md
  - Developers Guide: dev.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pytexas
      name: Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/pytexas-foundation
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jNPAbcNukj
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/PyTexas